### PR TITLE
Relax parser

### PR DESCRIPTION
**Pull request by mcgrof**
I've submitted some patches to upstream fio to try to address the issues with using the latest fio with fiovisualizer in a client/server relationship, however the effort has revealed to me that gfio is the solution we should be putting our attention towards. Nevertheless, here's a few changes which should help with fiovisualizer -- in case the project continues to move forward.

I however highly recommend attention to be given to gfio instead. The scaper model is inefficient, and gfio already has a community and much more capabilities.

### CODE REVIEW

**Comment by mcgrof** [comment]
fiovisualizer was startd prior to gfio? fiovisualizer's release date is 2015, gfio started in 2012. How do you figure?

gfio also provides *more* real-time data visualization given its architecture for data exchange is direct and fluid, it does not involve a parser.

Once a job is finished you also get all per job data, and a graph of Completion percentiles, Latency buckets *per job*. Have you run the latest gfio? If so can you be a bit more specific in documentation then on counters? Additionally I would recommend then to just implement what is missing into gfio. I see no reason not to.

**Comment by AndreyKudryavtsev** [comment]
It takes long time to release open source software :) 
If seriously, our goal is real-time reporting, I explained it in the last comment. We needed to "visualize" what happens in real-time, not after the fact test finished. GFIO does it great in the final reporting including per-job reports, super cool, but real-time.

**Comment by mcgrof** [comment]
Again, gfio *is* showing data more in realtime than in fiovisualizer. Its unclear how you think otherwise, can you explain? That is, gfio is showing graphing data *as time moves forward* right away, and the time interval can actually be changed, rather than having a static 1 second interval as currently statically set into fiovisualizer.

So far the only difference you seem to have pointed out is that fiovisualizer is *also* graphing each performance metrics per thread (internally in fio this as per the ini file jobs=number; and this is either process (fork()) or a pthread (if ini has 'thread')) Vs the overall performance of all threads.

Any use of realtime in context to distinguish fiovisualizer Vs gfio needs to be established as well, given from my review they both are plotting data in the same manner but gfio is much more configurable.

**Comment by AndreyKudryavtsev** [comment]
Sorry, if I wasn't clear, FIO Visualizer reports per-job performance with max/avg latency in real-time. GFIO doesn't to that in real-time. If you think I missed that somewhere, please, share.

**Comment by mcgrof** [comment]
I have a suggestion. How about we review the differences clearly, and based on this provide a roadmap to satisfy your requirements?

Let's start with how fiovisualizer gathers its data and what is currently plotted. Please correct me if I missed anything. For future analysis and comparison to gfio, please review the client thread_status() callback, and so for gfio gfio_thread_status_op() and for the native text client handle_ts(). 

With my changes now merged upstream for both fio/fiovisualizer we can now use fiovisualizer with fio with a remote backend, but let us focus first just on everything running locally first.

For a localhost setup (local backend and client) fiovisualizer relies on the backend helper thread helper_thread_main() to spit out stats in a loop, this is __show_running_run_stats(). This in turn is where fiovisualizer gets its data, when show_thread_status_terse() is called for each process/thread run.

gfio gets its data from the same loop, except the server ends it to the client via fio_server_send_ts() a few lines above, the difference is here:

                if (is_backend) {                                               
                        fio_server_send_job_options(opt_lists[i], i);           
                        fio_server_send_ts(ts, rs);                             
                        if (output_format & FIO_OUTPUT_TERSE)                   
                                show_thread_status_terse(ts, rs, &output[__FIO_OUTPUT_TERSE]);
                } else {                                                        
                        if (output_format & FIO_OUTPUT_TERSE)                   
                                show_thread_status_terse(ts, rs, &output[__FIO_OUTPUT_TERSE]);
                        if (output_format & FIO_OUTPUT_JSON) {                  
                                struct json_object *tmp = show_thread_status_json(ts, rs, opt_lists[i]);
                                json_array_add_value_object(array, tmp);        
                        }                                                       
                        if (output_format & FIO_OUTPUT_NORMAL)                  
                                show_thread_status_normal(ts, rs, &output[__FIO_OUTPUT_NORMAL]);
                } 

The difference between getting the per thread data between gfio and fiovisualizer though is that fiovisualizer parses the data output, and then from this plots it. gfio on the other hand receives the data, mind you in the *same* time iteration, but *avoids* parsing.

fiovisualizer also only parses this data:

| 6 | read_bandwidth |
| 7 | read_iops |
| 15 | read_clat_mean | 
| 47 | write_bandwidth | 
| 48 | write_iops | 23580 |
| 56 | write_clat_mean | 

Per print out, ie, it is not actually splitting out graphed data per job, its treating the data as aggregate collection, the column number 2 for instance (starting to count at 0), the jobname is not taken into consideration on fiovisualizer.

In fact, today's fio output doesn't even distinguish the job ids differently, I'll have to check if this is a bug or what. I'll later review what is exactly plotted on the main graph for gfio, and I'd like to determine what you really need / desire and how you see that the implementation on gfio is insufficient for your requirements.

If its just actually plotting on the main graph latency, this seems like a trivial addition.

**Comment by FlorianHeigl** [comment]
@mcgrof just read this PR since I was looking into an unrelated issue.
as a bystander your attitude seems uncourtly...
just because you have the impression that gfio is the way to move forward is not a reason to recommend to the devs here to simply drop everything and switch.

not to mention... what gfio community are you talking about?
either are fragile with what jobs they like and come with lack of maintenance and / or many important items left as TODOs.
fiovisualizer has at least thoughtful GUI design , gfio is the usualy thrown together OSS UI that is completely removed from good visualization.
Both SUCK visually and both have zero features aimed at making benchmarking efficient.

Both have NIL error handling and both have seen NIL testing (short of some cleanup commits here like yours).

Given all of that, it's very very hard to see how you decided to go on a minor vendetta against one.

As a matter of courtesy, you should really keep PRs and suggestions/doubts about the project direction separate. We all run across OSS projects that seem to want to damage their own future, but that has no place in a PR. A projects direction may be the concern of contributors, but none of that has a place in a PR.

**Comment by mcgrof** [comment]
> @mcgrof just read this PR since I was looking into an unrelated issue.
> as a bystander your attitude seems uncourtly...

I agree with that tact was not of most quality here, and for that I apologize.

> just because you have the impression that gfio is the way to move forward is not a reason to recommend to the devs here to simply drop everything and switch.

Perhaps, but I do believe we set ourselves in technical debt of not pointing out what is found when an approach can be flawed.

> not to mention... what gfio community are you talking about?

Its part of fio now. Mind you, gfio doesn't even have documentation.

> either are fragile with what jobs they like and come with lack of maintenance and / or many important items left as TODOs.
> fiovisualizer has at least thoughtful GUI design , gfio is the usualy thrown together OSS UI that is completely removed from good visualization.

We can agree do disagree.

> Both SUCK visually and both have zero features aimed at making benchmarking efficient.

I tend to agree.

> Both have NIL error handling and both have seen NIL testing (short of some cleanup commits here like yours).

Patches welcomed!

> Given all of that, it's very very hard to see how you decided to go on a minor vendetta against one.

It is not a vendetta, if you see the file I posted reviewing the technicality of my reasoning, it is full of details which I plan to merge to fio / gfio. Without this information one cannot possibly make a reasonable analysis on *how* to graph things properly.

> As a matter of courtesy, you should really keep PRs and suggestions/doubts about the project direction separate. 

I disagree. I'd welcome critical feedback on a project I maintain if someone can show me the path forward to a project no longer makes sense. In fact I'd welcome that heavily.

> We all run across OSS projects that seem to want to damage their own future, but that has no place in a PR.

It is not clear what you mean here. Do you meant that sometimes you can find projects which are driven despite the fact that they are on a  technical path which no longer makes sense?

It depends. Given the *complete* utter lack of documentation of gfio, and that even at the latest ALPSS conference *absolutely no one* was aware of it, I think we do have a technical and social debt to try to create awareness of differences in visualization projects which may help aim finding truth in which paths make more sense to improve technologies, and to also then see how we can come together on solutions which can be shared.

The critique here is not social, it is technical, to help improve design. For instance, a real python client which works *as* a client, *would* be a much better approach, and the documentation provided to explain this tries to justify this.

If I would have just tried to complain, without providing details, I can see your argument, but since real technical debt in terms of documentation is also being brought forward to help shine light in differences in paths, I believe my call for a change in a PR is justified.

> A projects direction may be the concern of contributors, but none of that has a place in a PR.

The point to the PR was to 1) fix issues 2) explain in technical detail *why* the current approach is flawed, and provide a technical discussion as to why that might be the case. I believe it has succeeded on both fronts.

**Pull request merged**
